from django.urls import path
from . import views

app_name = 'hr_working_hours'

urlpatterns = [
    path('', views.main, name='main'),
    path('loc_to_man_edit/<int:pk>', views.loc_to_man_edit, name='loc_to_man_edit'),
    path('loc_to_man_delete/<int:pk>', views.loc_to_man_delete, name='loc_to_man_delete'),
    path('LocToMan', views.LocToMan, name='LocToMan'),
    path('WorkerToLoc', views.WorkerToLoc, name='WorkerToLoc'),
    path('my_workers_in_loc/<int:location>', views.my_workers_in_loc, name='my_workers_in_loc'),
    path('my_workers_in_loc_edit/<int:location>/<str:worker>/<week_start>/<week_end>',
         views.my_workers_in_loc_edit, name='my_workers_in_loc_edit'),
    path('my_workers_in_loc_edit_single/<int:pk>', views.my_workers_in_loc_edit_single,
         name='my_workers_in_loc_edit_single'),
    path('my_workers_in_loc_create_single/<str:worker>', views.my_workers_in_loc_create_single,
         name='my_workers_in_loc_create_single'),
    path('my_workers_in_loc_create_single_inline/<str:worker>/<day_selected>',
         views.my_workers_in_loc_create_single_inline, name='my_workers_in_loc_create_single_inline'),
    path('my_workers_in_loc_edit_delete/<int:pk>', views.my_workers_in_loc_edit_delete,
         name='my_workers_in_loc_edit_delete'),
    path('worker_to_loc_edit', views.worker_to_loc_edit, name='worker_to_loc_edit'),
    path('worker_to_loc_edit_single/<int:pk>', views.worker_to_loc_edit_single,
         name='worker_to_loc_edit_single'),
    path('worker_to_loc_edit_single_delete/<int:pk>', views.worker_to_loc_edit_single_delete,
         name='worker_to_loc_edit_single_delete'),
    path('hr_reports', views.hr_reports, name='hr_reports'),
    path('hr_report_per_company_modal', views.hr_report_per_company_modal, name='hr_report_per_company_modal'),
    path('hr_report_per_location_modal', views.hr_report_per_location_modal, name='hr_report_per_location_modal'),
    path('hr_report_per_manager_modal', views.hr_report_per_manager_modal, name='hr_report_per_manager_modal'),
    path('hr_report_per_user_modal', views.hr_report_per_user_modal, name='hr_report_per_user_modal'),
    path('hr_report_edit_worker_modal', views.hr_report_edit_worker_modal, name='hr_report_edit_worker_modal'),
    path('hr_report_per_company/<str:company>/<week_start>/<week_end>', views.hr_report_per_company,
         name='hr_report_per_company'),
    path('hr_report_per_location/<int:location>/<week_start>/<week_end>', views.hr_report_per_location,
         name='hr_report_per_location'),
    path('hr_report_per_manager/<int:manager>/<week_start>/<week_end>', views.hr_report_per_manager,
         name='hr_report_per_manager'),
    path('hr_report_per_user/<int:worker>/<week_start>/<week_end>', views.hr_report_per_user,
         name='hr_report_per_user'),
    path('download_csv/<str:company>/<date_start>/<date_end>', views.download_csv, name='download_csv'),
    path('time_diff/<user>/<week_start>/<week_end>', views.time_diff, name='time_diff'),
    path('hr_accept_entries/<user>/<week_start>/<week_end>', views.hr_accept_entries, name='hr_accept_entries'),
    path('time_diff_inline/<int:pk>', views.time_diff_inline, name='time_diff_inline'),
    path('zero_extra_hours_inline/<int:pk>', views.zero_extra_hours_inline, name='zero_extra_hours_inline'),
    path('zero_extra_hours/<str:user>/<week_start>/<week_end>', views.zero_extra_hours, name='zero_extra_hours'),
    path('accept_entry_inline/<int:pk>', views.accept_entry_inline, name='accept_entry_inline'),
    path('create_entry_inline/<entry_date>/<entry_time>/<str:worker>', views.create_entry_inline,
         name='create_entry_inline'),
    path('change_entry_inline/<int:pk>/<start_time>', views.change_entry_inline, name='change_entry_inline'),
    path('change_leaving_inline/<int:pk>/<stop_time>', views.change_leaving_inline, name='change_leaving_inline'),
    path('last_day_list', views.last_day_list, name='last_day_list'),
    path('last_day_create', views.last_day_create, name='last_day_create'),
    path('last_day_edit/<int:pk>', views.last_day_edit, name='last_day_edit'),
    path('last_day_delete/<int:pk>', views.last_day_delete, name='last_day_delete'),
    ## managers to workers ##
    path('managers_workers_add', views.managers_workers_add, name='managers_workers_add'),
    path('managers_workers_edit/<int:worker_id>', views.managers_workers_edit, name='managers_workers_edit'),
    path('ManToWork/<int:worker>/<int:manager>', views.ManToWork, name='ManToWork'),
    path('company_serialize', views.company_serialize, name='company_serialize'),
    path('location_serialize', views.location_serialize, name='location_serialize'),
    path('manager_serialize', views.manager_serialize, name='manager_serialize'),
]
